### PR TITLE
Bozkurt

### PR DESCRIPTION
**Pull request by zekeriyaarslantas**

### CODE REVIEW

**Comment by zekeriyaarslantas** [comment]
24/10/2022 z b

**Review by zekeriyaarslantas — COMMENTED** [review]
24/10/2022 zb

**Comment by MUHAMMED-FURKAN-YILMAZ** [comment]
68854623664a410979103f9ea4595d3497311641

**Review by ahmeet80 — APPROVED** [review]

**Comment by ahmeet80** [comment]
Tamam

**Pull request merged**
